### PR TITLE
require fs properly

### PR DESCRIPTION
**Pull request by Frijol**
@johnnyman727 should I also add back that passkey line?

### CODE REVIEW

**Comment by johnnyman727** [comment]
Yes, this will have to pass in the provided passphrase to the `connect` method inside `ssh-deploy.js`

**Comment by Frijol** [comment]
Is it not? What needs to change?

**Comment by johnnyman727** [comment]
My mistake- you have it in there. Can you confirm that it works for keys without passphrases as well? Once you do that I think it's good to merge.

**Comment by Frijol** [comment]
Works great! Merging.

**Pull request merged**
